default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  primary:
    <<: *default
    database: app_primary_development

  primary_replica:
    <<: *default
    database: app_primary_development_replica
    replica: true

  accounting_primary:
    <<: *default
    database: accounting_development
    migrations_paths: db/accounting_migrate

  accounting_replica:
    <<: *default
    database: accounting_development_replica
    replica: true

  financial_institutions_primary:
    <<: *default
    database: financial_institutions_development
    migrations_paths: db/financial_institutions_migrate

  financial_institutions_replica:
    <<: *default
    database: financial_institutions_development_replica
    replica: true

  auths_primary:
    <<: *default
    database: auths_development
    migrations_paths: db/auths_migrate

  auths_replica:
    <<: *default
    database: auths_development_replica
    replica: true

test:
  primary:
    <<: *default
    database: app_primary_test

  primary_replica:
    <<: *default
    database: app_primary_test_replica
    replica: true

  accounting_primary:
    <<: *default
    database: accounting_test
    migrations_paths: db/accounting_migrate

  accounting_replica:
    <<: *default
    database: accounting_test_replica
    replica: true

  financial_institutions_primary:
    <<: *default
    database: financial_institutions_test
    migrations_paths: db/financial_institutions_migrate

  financial_institutions_replica:
    <<: *default
    database: financial_institutions_test_replica
    replica: true

  auths_primary:
    <<: *default
    database: auths_test
    migrations_paths: db/auths_migrate

  auths_replica:
    <<: *default
    database: auths_test_replica
    replica: true

production:
  primary:
    <<: *default
    database: kiphodan_production
    username: kiphodan
    password: <%= ENV["KIPHODAN_DATABASE_PASSWORD"] %>

  primary_replica:
    <<: *default
    database: kiphodan_production_replica
    replica: true

  accounting:
    <<: *default
    database: kiphodan_production_accounting
    migrations_paths: db/accounting_migrate

  accounting_replica:
    <<: *default
    database: kiphodan_production_accounting_replica
    replica: true

  financial_institutions:
    <<: *default
    database: kiphodan_production_financial_institutions
    migrations_paths: db/financial_institutions_migrate

  financial_institutions_replica:
    <<: *default
    database: kiphodan_production_financial_institutions_replica
    replica: true

  auths:
    <<: *default
    database: kiphodan_production_auths
    migrations_paths: db/auths_migrate

  auths_replica:
    <<: *default
    database: kiphodan_production_auths_replica
    replica: true

  cache:
    <<: *default
    database: kiphodan_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: kiphodan_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: kiphodan_production_cable
    migrations_paths: db/cable_migrate
