default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  port: <%= ENV.fetch("PGPORT", 5432) %>

development:
  accounting:
    <<: *default
    database: accounting_development
    migrations_paths: db/accounting_migrate

  accounting_replica:
    <<: *default
    database: accounting_development_replica
    replica: true

  financial_institutions:
    <<: *default
    database: financial_institutions_development
    migrations_paths: db/financial_institutions_migrate

  financial_institutions_replica:
    <<: *default
    database: financial_institutions_development_replica
    replica: true

test:
  accounting:
    <<: *default
    database: accounting_test
    migrations_paths: db/accounting_migrate

  accounting_replica:
    <<: *default
    database: accounting_test_replica
    replica: true

  financial_institutions:
    <<: *default
    database: financial_institutions_test
    migrations_paths: db/financial_institutions_migrate

  financial_institutions_replica:
    <<: *default
    database: financial_institutions_test_replica
    replica: true

production:
  primary: &primary_production
    <<: *default
    database: kiphodan_production
    username: kiphodan
    password: <%= ENV["KIPHODAN_DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: kiphodan_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: kiphodan_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: kiphodan_production_cable
    migrations_paths: db/cable_migrate
